### ISSUE TITLE
I need your contact

### ISSUE THREAD

**Issue by ottersmans** [Tecnio/strezz-central#1]
do u have discord or email? I really have to talk with you privately

**Comment by Tecnio** [comment]
I have Discord but I have friend requests disabled, if you could send me your Discord would be better.

**Comment by ottersmans** [comment]
I'll give you my Discord on your email, whats ur email?

**Comment by ottersmans** [comment]
Im a very private person

**Comment by Strezzed** [comment]
sheeeeeeesh

**Comment by Tecnio** [comment]
> sheeeeeeesh

sheeeeesh
